services:
# ------------------------------------------------------------------------------------------------------------------------
# by command "./sat run-docker-compose" will run:
# docker-compose up --file ./path/to/file/docker-compose --project-directory ./path/to/file/docker-compose --verbose --project-name anyName
  docker-compose:
    - name: "run-docker-compose"
      path: "./path/to/file/docker-compose"
      project-directory: "./path/to/file/docker-compose"
      project-name: "anyName"
      description: "run docker compose data"
      verbose: true
      log-level: "DEBUG"
      command: "up"

# ------------------------------------------------------------------------------------------------------------------------
# by command "./sat fresh-img" will run:
# docker pull node:10
  pull:
    - name: "fresh-img"
      image: "node"
      version: "10"
      description: "pull node 10"

# ------------------------------------------------------------------------------------------------------------------------
# by command "./sat composer-command composer i" will run:
# docker run --rm --workdir=/home/www-data --name composer composer:1.9 /bin/bash -c composer --version; composer i
  run:
    - name: "composer-command"
      clean-up: true
      image: "composer"
      version: "1.9"
      workdir: "/home/www-data"
      description: "install composer dependencies"
      pre-commands:
        - "composer --version"

# ------------------------------------------------------------------------------------------------------------------------
# by command "./sat console php -v" will run:
# docker exec project /bin/bash -c cd /home; ls -la; php -v
  exec:
    - name: "console"
      container-name: "project"
      work-dir: "/home/www/project"
      description: "exec console for project"
      pre-commands:
        - "cd /home"
        - "ls -la"

# ------------------------------------------------------------------------------------------------------------------------
# by command "./sat macros init" will run consistently 3 command from commands section.
# that commands will run from sections described above
macros:
  - name: "multi-run"
    commands:
      - "fresh-img"
      - "composer-command composer i"
      - "console php -v"
