services:
  run:
    - name: "composer-cmd"
      clean-up: true
      image: "composer"
      description: "work with composer dependencies"

    - name: "node-cmd"
      clean-up: true
      image: "node"
      version: "12"
      description: "work with node dependencies"

macros:
  - name: "install-all"
    description: "install all deps"
    commands:
      - "composer-cmd composer i --ignore-platform-reqs"
      - "node-cmd node i"
