services:
  - name: "yarn"
    image: "node"
    version: "14"
    user-id: "1000"
    image-command: "yarn"
    work-dir: "/home/node"
    volumes:
      - "$(pwd):/home/node"
      - "$(pwd)/cache:/tmp"

  - name: "fresh-img"
    command: "pull"
    image: "node"
    version: "10"

  - name: "my-image"
    detach: true
    clean-up: true
    image: "gitlab.com/my/image"
    environment-variables:
      - "PHP_IDE_CONFIG=serverName=192.168.0.1"
    volumes:
      - "$(pwd):/home/www"
    dns:
      - "8.8.8.8"
    ports:
      - "127.0.0.1:443:443"
      - "80:80"

  - name: "composer"
    version: "2"
    user-id: "1000"
    image-command: "composer"
    work-dir: "/home/www-data"
    volumes:
      - "$(pwd):/home/www-data"
      - "$(pwd)/cache:/tmp"

macros:
  - name: "init"
    commands:
      - "composer i --ignore-platform-reqs"
      - "yarn install"
