commands:
  composer:
    version: "2"
    cache-dir: "/some/path/to/cache"
    work-dir: "/home/www-data"
    environment-variables:
      - "USER_ID=1000"
    add-hosts:
      - "host.docker.internal:127.0.0.1"
    ports:
      - "8080:8080"
    volumes:
      - "/some/path/to/volume:/home/www-data"
    dns:
      - "8.8.8.8"
    pre-commands:
      - "git config --global http.sslVerify false" ## Это для того чтобы сертификаты не прокидывать в контейнер (нужен root в этом контейнере)
    post-commands:
      - "chown -R $USER_ID:$USER_ID /home/www-data"  ## из environment-variables берем $USER_ID пользователя своей системы и выставляем права на вендорные директории (можно конечно напрямую задать или из .env)
    config:
      process-timeout: "400"
      optimize-autoloader: "false"
      repositories:
        - "http-basic.gitlab.your-private-repo.com {GITLAB_NAME} {GITLAB_TOKEN}" ## приватный репозиторий {GITLAB_NAME} {GITLAB_TOKEN} - задаются в .env GITLAB_NAME=name
