commands:
  composer:
    version: "2"
    cache-dir: "/some/path/to/cache"
    user-id: "501"
    work-dir: "/home/www-data"
    environment-variables:
      - "SOME_VAR=someVal"
    add-hosts:
      - "host.docker.internal:127.0.0.1"
    ports:
      - "8080:8080"
    volumes:
      - "/some/path/to/volume:/home/www-data"
    dns:
      - "8.8.8.8"
    post-commands:
      - "composer --version"
    pre-commands:
      - "composer --version"
    config:
      process-timeout: "400"
      optimize-autoloader: "false"
      repositories:
        - "http-basic.github.com mamau some-token"
        - "http-basic.gitlab.com mamau some-token"
